[package]
name = "hyper-alpine"
version = "0.1.0"
authors = ["Mason Ginter <mason@dagint.com>"]
edition = "2018"

[dependencies]
hyper = {version = "0.14", features = ["full"]}
hyper-tls = "0.5"
tokio = {version = "1.4", features = ["full"]}